### ISSUE TITLE
Unable to run the Eval project from VS 2019 IDE.

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildTools#1]
Works fine when compiled and run on the command line:
```
C:\work\MSBuildTools\src\Evaluation [main ≡]> dotnet build
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\work\MSBuildTools\src\Evaluation\eval.csproj (in 210 ms).
  eval -> C:\work\MSBuildTools\src\Evaluation\bin\Debug\net472\eval.exe

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.07
C:\work\MSBuildTools\src\Evaluation [main ≡]> .\bin\Debug\net472\eval.exe c:\xyz\tip\Services\Platform\AdminService\AdminService.csproj | select -First 3
AdminSecret\IAdminSecretProvider.cs
AdminSecret\AdminSecretProvider.cs
Billing\BillingScheduler.cs
C:\work\MSBuildTools\src\Evaluation [main ≡]>
```
However, it fails when compiled and run from the VS 2019 IDE. The `simpleCacheType` object in the `Evaluator` constructor is `null` - https://github.com/KirillOsenkov/MSBuildTools/blob/fc5360417ba141c40bed05fce99afa09d407583d/src/Evaluation/Eval.cs#L52

**Comment by KirillOsenkov** [comment]
@MarkKharitonov when you hit this exception in the debugger, what is the path to loaded MSBuild binaries in the Debug -> Windows -> Modules?

I've tried with both VS 2022 and VS 2019 and it all works fine for me.

Here are my examples:
![image](https://user-images.githubusercontent.com/679326/142713565-8e8ae7a3-1c2d-4546-aad8-0939ca290552.png)

![image](https://user-images.githubusercontent.com/679326/142713582-7af544a3-673e-404d-9db0-98483d6d6f36.png)

You can switch which MSBuild version to load using this code:

```
        var instances = MSBuildLocator.QueryVisualStudioInstances();
        var instance = instances.Where(i => i.Version.Major == 16).FirstOrDefault();
        MSBuildLocator.RegisterInstance(instance);
```

It might be that you have super old MSBuild binaries installed in the GAC. Try `gacutil /l microsoft.build` (and so for each MSBuild binary) to see if it's the case. You'll need to unGAC them if so.

**Comment by MarkKharitonov** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/489792/142714945-796adb38-37bb-43e4-ad12-06331d4c6667.png)
For some reason they are from VS 2017. I need to check why. Should not be the case. Will be back with results.

Checked the GAC, there is indeed an ancient version there, but the modules are loaded from the VS 2017 build tools folder, not GAC. Which is weird nonetheless, because VS 2017 is not even in the PATH. And I checked with the Process Explorer. 

Here is the fusion log:
```
=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/work/MSBuildTools/src/Evaluation/bin/Debug/net472/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = eval.exe
Calling assembly : Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\work\MSBuildTools\src\Evaluation\bin\Debug\net472\eval.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 15.1.0.0 redirected to 15.1.0.0.
LOG: Post-policy reference: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/work/MSBuildTools/src/Evaluation/bin/Debug/net472/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/work/MSBuildTools/src/Evaluation/bin/Debug/net472/Microsoft.Build.Framework/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/work/MSBuildTools/src/Evaluation/bin/Debug/net472/Microsoft.Build.Framework.EXE.
LOG: Attempting download of new URL file:///C:/work/MSBuildTools/src/Evaluation/bin/Debug/net472/Microsoft.Build.Framework/Microsoft.Build.Framework.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/Microsoft.Build.Framework.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Where-ref bind Codebase does not match what is found in default context. Keep the result in LoadFrom context.
LOG: Binding succeeds. Returns assembly from C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll.
LOG: Assembly is loaded in LoadFrom load context.
```

I started VS from the VS 2019 developer console and it worked just fine - the assembles were loaded from the VS 2019 directory. But, if I start VS 2019 by clicking the pinned icon on the taskbar - the assembles are loaded from VS 2017, even though I am starting VS 2019. This is super weird and I tend to believe it is a bug in the locator. The scenario is:

1. Have VS 2017 installed locally.
2. Do not have any VS paths in the global PATH (neither user nor system)
3. Open VS 2019 from the start menu, NOT the dev console.

**Comment by KirillOsenkov** [comment]
Note that you have VS 2017 Build Tools installed, not just VS.

MSBuildLocator doesn't know which version you prefer, so you need to tell it that you don't want to use VS 2017 build tools. 

Use the snippet like this:

```
        var instances = MSBuildLocator.QueryVisualStudioInstances();
        var instance = instances.Where(i => i.Version.Major >= 16).FirstOrDefault();
        MSBuildLocator.RegisterInstance(instance);
```

**Comment by KirillOsenkov** [comment]
Also, none of the MSBuild binaries should be in the GAC.

See here:
https://github.com/dotnet/msbuild/issues/5183#issue-584585472

**Comment by KirillOsenkov** [comment]
As far as I can see, none of the above indicates an inherent problem with my sample. Let me know if I'm missing anything.

**Comment by MarkKharitonov** [comment]
No, you answered it. I thought the msbuild locator would chose the highest version, but you are right that it may not be what the dev wants and so it should be provided.
